@startuml
InvokerInvocationHandler -> MockClusterInvoker: invoke
MockClusterInvoker -> AbstractClusterInvoker: list
AbstractClusterInvoker -> AbstractDirectory: list
AbstractDirectory -> RegistryDrectory: doList

@enduml