@startuml
InvokerInvocationHandler -> MockClusterInvoker: invoke
MockClusterInvoker -> AbstractClusterInvoker: invoke
AbstractClusterInvoker -> AbstractDirectory: list
AbstractDirectory -> RegistryDirectory: doList
AbstractClusterInvoker <-- RegistryDirectory: invokes
AbstractClusterInvoker -> FailoverCluster: doInvoke

@enduml